POST   http://localhost:4000/app/signupCustomer
Content-Type: application/json


 {
    "fullName":"12312nikhil123",
    "email":"v@g.com",
    "phoneNo":"7789987898",
     "gender":"male",
     "occupation":"student",
     "password":"vamshipass",
     "experience":"none"

 }


